### ISSUE TITLE
dose_rayonnements_telluriques ne marche pas 

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#101]
Le csv dose_rayonnements_telluriques
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Roaming\Python\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\LifeSCORE.py", line 538, in <lambda>
    command=lambda: ville(entree,msg_ville,fenetre),text="Recherche",font=('Arial Black',30))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\LifeSCORE.py", line 607, in ville
    w_score(Donnees_ville,fenetre)
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\LifeSCORE.py", line 629, in w_score
    score = Donnees_ville.note_finale() # Provisoire
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\classes.py", line 686, in note_finale
    self.prepa_recup_donnees(liste_csv, id) #Ancienne méthode, pas très rapide avec bcp de CSV
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\classes.py", line 737, in prepa_recup_donnees
    resultat = self.recuperation_donnees(id, liste_csv)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\classes.py", line 392, in recuperation_donnees
    return Donnees.recup_donnees_simple_affine(self, csv, liste_csv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\classes.py", line 356, in recup_donnees_simple_affine
    nombre = Donnees.recup_donnees_simple(self, csv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "C:\Users\natha\AppData\Roaming\Python\Python311\site-packages\pandas\io\parsers\base_parser.py", line 917, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['code_insee']
PS C:\Users\natha\Documents\GitHub\Life-SCORE>

**Comment by bosy0** [comment]
non ça marche pas, c'est trop chiant ptdrr
