### ISSUE TITLE
Ne peut pas modifier la fréquence de maj

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#123]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Roaming\Python\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\LifeSCORE.py", line 498, in <lambda>
    command=lambda:modifier_fichier_dico("FREQ_MAJ", round(abs(float(entree_frequence_maj.get()))*86400),message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Life-SCORE\code\classes.py", line 183, in modifier_fichier_dico
    if fichier[0] == "/": # pour eviter un bug avec os.path.join()
       ~~~~~~~^^^
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1708, in cget
    return self.tk.call(self._w, 'cget', '-' + key)
                                         ~~~~^~~~~
TypeError: can only concatenate str (not "int") to str

**Comment by ThorsThunder04** [comment]
C'etait a cause du parametre fichier qu'on a ajouté. 
![image](https://user-images.githubusercontent.com/87436831/230791941-2b8c3860-b90b-426c-ba94-c747486f063b.png)

Donc fichier recvais un objet tkinter au lieux du string options. J'ai fix en ajoutant le chemin options.
![image](https://user-images.githubusercontent.com/87436831/230791994-cf68fb05-4c84-4966-9ac3-3ec73301ac7c.png)
