### ISSUE TITLE
Manque de "pattern" de split qui cause un erreur.

### ISSUE THREAD

**Issue by ThorsThunder04** [The-Weather-TEAM/Life-SCORE#124]
En recherchant la ville "salies" j'ai rencontré un erreur dans classes.py, ou enfait on split le nom du ville, mais on ne dit jamais par quoi le split. Et jsp par quoi le split, donc voila le problem.

J'assigne toi Nathan vue que ça vien de ton commit https://github.com/The-Weather-TEAM/Life-SCORE/commit/8567dddaf53c86657f202b2c6f30f56c732013e6

![image](https://user-images.githubusercontent.com/87436831/230883913-d3179e6b-c29f-4b63-bacd-b244adea64a1.png)

```
Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 531, in _clicked
    self._command()
  File "G:\My Drive\0prog_and_IT\prog_langs\python\Life-SCORE\code\LifeSCORE.py", line 621, in <lambda>
    command=lambda: analyse_ville(entree,msg_Ville,fenetre,btn_Entree),text="Recherche ",font=(polices[0],30, 'bold'),image=image_btn_chercher)
  File "G:\My Drive\0prog_and_IT\prog_langs\python\Life-SCORE\code\LifeSCORE.py", line 692, in analyse_ville
    liste_Voisins = Donnees_ville.k_plus_proches_voisins(10,msg,fenetre)
  File "G:\My Drive\0prog_and_IT\prog_langs\python\Life-SCORE\code\classes.py", line 686, in k_plus_proches_voisins
    note = Donnees(nom,insee).note_finale(meteo = False)
  File "G:\My Drive\0prog_and_IT\prog_langs\python\Life-SCORE\code\classes.py", line 896, in note_finale
    self.prepa_recup_donnees(id) #Ancienne méthode, pas très rapide avec bcp de CSV
  File "G:\My Drive\0prog_and_IT\prog_langs\python\Life-SCORE\code\classes.py", line 941, in prepa_recup_donnees
    resultat = self.recuperation_donnees(id)
  File "G:\My Drive\0prog_and_IT\prog_langs\python\Life-SCORE\code\classes.py", line 532, in recuperation_donnees
    return Donnees.recup_donnees_compter_par_habitant(self, csv)
  File "G:\My Drive\0prog_and_IT\prog_langs\python\Life-SCORE\code\classes.py", line 444, in recup_donnees_compter_par_habitant
    self.ville = re.split(self.ville)[0]
TypeError: split() missing 1 required positional argument: 'string'
```

**Comment by bosy0** [comment]
je m'en occupe
