### ISSUE TITLE
Arrondissements Paris ne marchent pas

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#25]
Il y a que le 1er qui marche, les autres affichent une page blanche

**Comment by bosy0** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\LifeSCORE.py", line 270, in <lambda>
    btn_entree = Button(windowQuestion,width=20, height=3, command=lambda: ville(entree,msg_ville,windowQuestion), bg='#B9F7D0', text="Recherche")
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\LifeSCORE.py", line 318, in ville
    w_score(ville)
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\LifeSCORE.py", line 338, in w_score
    score = int(Donnees_ville.note_finale()) #Provisoire
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\classes.py", line 323, in note_finale
    tableau.append(self.note_sport())
                   ^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\classes.py", line 285, in note_sport
    nbr_etab_sportifs = rangee.values[0][1]
                        ~~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by bosy0** [comment]
@Spaghet34 ça remarche dcp ?

**Comment by bosy0** [comment]
yep bien joué bg

**Comment by Spaghet34** [comment]
Merci a moins que les villes rajoutent des arrondissements c'est bon

**Comment by bosy0** [comment]
mdrr je pense que c'est dans un petit moment ouais
