### ISSUE TITLE
ChunkedEncodingError BUG

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#51]
Si on coupe la co en plein téléchargement ça plante, je n'arrive pas à trouver de solutions pour l'instant je vais me renseigner

PowerShell 7.3.1
PS C:\Users\natha\Documents\GitHub\Weather-NSI> & C:/Users/natha/AppData/Local/Programs/Python/Python311/python.exe c:/User
s/natha/Documents/GitHub/Weather-NSI/code/update.py
6%   -  gares  -> Fichier téléchargé
13%  -  festivals  -> Fichier téléchargé
Traceback (most recent call last):
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 444, in _error_
catcher
    yield
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 831, in read_ch
unked
    chunk = self._handle_chunk(amt)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 775, in _handle
_chunk
    value = self._fp._safe_read(amt)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 632, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(2254 bytes read, 7986 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 816, in generate

    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 816, in read_ch
unked
    with self._error_catcher():
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 461, in _error_
catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(2254 bytes read, 7986 more expected)', IncompleteRead
(2254 bytes read, 7986 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\update.py", line 556, in <module>
    print(executer()) # Retourne s'il y a une erreur qui empêche le programme de tourner
          ^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\update.py", line 286, in executer
    recup_csv_internet = requests.get(lien, allow_redirects=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in reques
t
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 723, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 723, in <listc
omp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 266, in resolv
e_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 745, in send
    r.content
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(2254 bytes read, 7986 more expected)', IncompleteRead(2254 byt
es read, 7986 more expected))

**Comment by Spaghet34** [comment]
Mets un try : except et si ya erreur juste print ('le programme n'a pas pu se lancer à cause d'une erreur de connexion car les fichiers sont corrompus')

**Comment by bosy0** [comment]
C'était une dignerie même avec un try ça marchait pas mais c'est corrigé, j'ai vu que twitter et mozilla avait le même problème sur leurs codes mdrrr
