### ISSUE TITLE
le csv des juridictions fait planter le programme

### ISSUE THREAD

**Issue by Farenc21** [The-Weather-TEAM/Life-SCORE#88]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Raf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\customtkinter\windows\widgets\ctk_button.py", line 531, in _clicked
    self._command()
  File "c:\Users\Raf\Life-SCORE\code\LifeSCORE.py", line 924, in <lambda>
    btn_ok = interface.CTkButton(fenetrePrincipale, height=int(fenetrePrincipale.winfo_screenheight()/10), command=lambda:telechargement(btn_ok,fenetrePrincipale), text="Continuer",font=('Arial Black',30)) #appele la fonction question1
  File "c:\Users\Raf\Life-SCORE\code\LifeSCORE.py", line 205, in telechargement
    erreur_maj = update.executer(progressbar,windowDownload,msg_aide,message_pourcentage)
  File "c:\Users\Raf\Life-SCORE\code\update.py", line 240, in executer
    recup_version = ligne.values[0][1]                       # Retourne la version du fichier
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by Farenc21** [comment]
résolu en modifiant les noms /!\ aux accents dans les fichiers !!! /!\
