### ISSUE TITLE
Erreur après le dernier commit ?

### ISSUE THREAD

**Issue by Farenc21** [The-Weather-TEAM/Life-SCORE#94]
Il me semble que l'erreur provient du dernier commit de @fredericmarquet et j'ai aucune idée de comment on règle ça avec le .json 

```Traceback (most recent call last):
  File "c:\Users\Raf\Life-SCORE\code\LifeSCORE.py", line 72, in <module>
    import update # Importe les fonctions et met à jour les modules en meme temps
    ^^^^^^^^^^^^^
  File "c:\Users\Raf\Life-SCORE\code\update.py", line 55, in <module>
    from classes import is_connected as connexion
  File "c:\Users\Raf\Life-SCORE\code\classes.py", line 49, in <module>
    infos_csv = json.load(fichier_json)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raf\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Raf\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raf\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raf\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 51 column 83 (char 3626)```

**Comment by Farenc21** [comment]
Réglé c'était une petite erreur de syntaxe rien de bien méchant :)

**Comment by fredericmarquet** [comment]
Oui c'est possible, en effet la base de donné est toujours en cours.
